name: testing the go project

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: setup go version 1.19
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      
      - name: build go project
        run: go build hello.go